POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Guy MissingNumber"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "555-555-5555"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Arto Hellas",
  "number": "123-123-1234"
}